[package]
name = "d9"
version = "0.1.0"
edition = "2024"

[lib]
name = "d9_lib"
path = "src/lib.rs"

[[bin]]
name = "d9"
path = "src/main.rs"

[dependencies]
geo = { version = "0.32", default-features = false }
